# vegasword's config file
theme = "handmade"
[editor]
line-number = "relative"
mouse = false
auto-format = false
cursorline = true
completion-trigger-len = 1
rulers = [80]
[editor.statusline]
left = ["mode", "position", "selections"]
center = ["diagnostics", "file-name"]
right = ["spinner", "file-encoding", "file-line-ending"]
separator = "|"
[editor.auto-pairs]
'{' = '}'
'[' = ']'
'(' = ')'
[keys.normal]
C-s = ":w"
C-m = ":sh build debug"
C-M = ":sh build"
C-r = ":sh run"
C-C = ":sh clean"
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
[keys.insert]
"C-i" = "normal_mode"
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
[keys.select]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
